# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # 使用する.NETのバージョン

      - name: Restore dependencies
        run: dotnet restore

      - name: Get the version
        run: |
          echo "VERSION=$(grep '<Version>' git-local-repository-listing/git-local-repository-listing.csproj | head -1 | awk -F'[<>]' '{print $3}')" >> $GITHUB_ENV

      - name: Publish Windows x64 Runtime Dependent
        run: |
          dotnet publish git-local-repository-listing/git-local-repository-listing.csproj --configuration Release --output publish/windows-runtime-dependent --runtime win-x64 --self-contained false
          zip -r -j lepol-windows-x64-runtime-dependent-${{ env.VERSION }}.zip publish/windows-runtime-dependent src/lepos.bash

      - name: Publish Windows x64 Self-Contained
        run: |
          dotnet publish git-local-repository-listing/git-local-repository-listing.csproj --configuration Release --output publish/windows-self-contained --runtime win-x64 --self-contained true
          zip -r -j lepol-windows-x64-self-contained-${{ env.VERSION }}.zip publish/windows-self-contained src/lepos.bash

      - name: Publish Linux x64 Runtime Dependent
        run: |
          dotnet publish git-local-repository-listing/git-local-repository-listing.csproj --configuration Release --output publish/linux-runtime-dependent --runtime linux-x64 --self-contained false
          zip -r -j lepol-linux-x64-runtime-dependent-${{ env.VERSION }}.zip publish/linux-runtime-dependent src/lepos.bash

      - name: Publish Linux x64 Self-Contained
        run: |
          dotnet publish git-local-repository-listing/git-local-repository-listing.csproj --configuration Release --output publish/linux-self-contained --runtime linux-x64 --self-contained true
          zip -r -j lepol-linux-x64-self-contained-${{ env.VERSION }}.zip publish/linux-self-contained src/lepos.bash


      - name: Release with action-gh-release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lepol-windows-x64-runtime-dependent-${{ env.VERSION }}.zip
            lepol-windows-x64-self-contained-${{ env.VERSION }}.zip
            lepol-linux-x64-runtime-dependent-${{ env.VERSION }}.zip
            lepol-linux-x64-self-contained-${{ env.VERSION }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
